src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $date_reservation = null;

    #[ORM\ManyToMany(targetEntity: Livre::class, inversedBy: 'reservations')]
    private Collection $livres;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Admin $user = null;


    public function __construct()
    {
        $this->livres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getDateReservation(): ?\DateTimeImmutable
    {
        return $this->date_reservation;
    }

    #[ORM\PrePersist]
    public function setDateReservation()
    {
        $this->date_reservation = new \DateTimeImmutable();
    }

    /**
     * @return Collection<int, Livre>
     */
    public function getLivres(): Collection
    {
        return $this->livres;
    }

    public function addLivre(Livre $livre): self
    {
        if (!$this->livres->contains($livre)) {
            $this->livres->add($livre);
        }

        return $this;
    }

    public function removeLivre(Livre $livre): self
    {
        $this->livres->removeElement($livre);

        return $this;
    }

    public function __toString(): string
    {
        return (string) $this->id . " - " . $this->date_reservation->format('Y-m-d');
    }

    public function getUser(): ?Admin
    {
        return $this->user;
    }

    public function setUser(?Admin $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            // ->add('date_reservation')
            ->add('livres')
            ->add('user');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Repository\ReservationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/reservation')]

class ReservationController extends AbstractController
{
    #[IsGranted('ROLE_ADMIN')]
    #[Route('/', name: 'app_reservation_index', methods: ['GET'])]
    public function index(ReservationRepository $reservationRepository): Response
    {
        return $this->render('reservation/index.html.twig', [
            'reservations' => $reservationRepository->findAll(),
        ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/new', name: 'app_reservation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ReservationRepository $reservationRepository): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reservationRepository->save($reservation, true);

            return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/{id}', name: 'app_reservation_show', methods: ['GET'])]
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }


    #[IsGranted('ROLE_ADMIN')]
    #[Route('/{id}/edit', name: 'app_reservation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reservation $reservation, ReservationRepository $reservationRepository): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reservationRepository->save($reservation, true);

            return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/{id}', name: 'app_reservation_delete', methods: ['POST'])]
    public function delete(Request $request, Reservation $reservation, ReservationRepository $reservationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $reservation->getId(), $request->request->get('_token'))) {
            $reservationRepository->remove($reservation, true);
        }

        return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('app_reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
	<button class="btn btn-primary">Delete</button>
</form>

templates/reservation/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reservation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reservation{% endblock %}

{% block body %}
    <h1>Edit Reservation</h1>

    {{ include('reservation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_reservation_index') }}">back to list</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}

templates/reservation/errorReservation.html.twig
{% extends 'base.html.twig' %}


{% block body %}
	<div class="container">
		<h1>
			Impossible de réserver car vous n'avez pas les accès !
		</h1>
		<p>
			Retour a la page principale :
			<a href="{{ path('app_livre_index') }}">Pas d'acceuil</a>
		</p>
	</div>
{% endblock %}

templates/reservation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation index
{% endblock %}

{% block body %}
	<div class="container">
		<h1 class="m-5">Liste des réservations
			<a href="{{ path('app_reservation_new') }}">
				<button type="button" class="btn btn-primary">Créer</button>
			</a>
		</h1>
		<table class="table">
			<thead>
				<tr>
					<th>Id</th>
					<th>Titre du livre</th>
					<th>Nom du reserveur</th>
					<th>Date de réservation</th>
				</tr>
			</thead>
			<tbody>
				{% for reservation in reservations %}
					<tr>
						<td>{{ reservation.id }}</td>
						{% for livre in reservation.livres %}
							<td>{{livre.titre}}</td>
						{% endfor %}
						<td>{{reservation.user}}</td>
						<td>{{ reservation.dateReservation ? reservation.dateReservation|date('d/m/Y') : '' }}</td>
						<td class="d-flex gap-1">
							<a href="{{ path('app_reservation_show', {'id': reservation.id}) }}">
								<button type="button" class="btn btn-primary">Voir</button>
							</a>
							<a href="{{ path('app_reservation_edit', {'id': reservation.id}) }}">
								<button type="button" class="btn btn-primary">Modifier</button>
							</a>
							{{ include('reservation/_delete_form.html.twig') }}
						</td>
					</tr>
				{% else %}
					<tr>
						<td colspan="3">Pas réservation en cours</td>
					</tr>
					<a href="{{ path('app_reservation_new') }}">
						<button type="button" class="btn btn-primary">Créer</button>
					</a>
				{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock %}

templates/reservation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reservation{% endblock %}

{% block body %}
    <h1>Create new Reservation</h1>

    {{ include('reservation/_form.html.twig') }}

    <a href="{{ path('app_reservation_index') }}">back to list</a>
{% endblock %}

templates/reservation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation
{% endblock %}

{% block body %}
	<h1>Reservation</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ reservation.id }}</td>
			</tr>
			<tr>
				<th>Date_reservation</th>
				<td>{{ reservation.dateReservation ? reservation.dateReservation|date('Y-m-d') : '' }}</td>
			</tr>
		</tbody>
	</table>

	<a href="{{ path('app_reservation_index') }}">back to list</a>

	<a href="{{ path('app_reservation_edit', {'id': reservation.id}) }}">edit</a>

{% endblock %}