src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LivreRepository::class)]
class Livre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    private ?string $auteur = null;

    #[ORM\Column(length: 255)]
    private ?string $editeur = null;

    #[ORM\Column(length: 255)]
    private ?string $genre = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $date_publication = null;


    #[ORM\ManyToMany(targetEntity: Emprunt::class, mappedBy: 'livres')]
    private Collection $emprunts;

    #[ORM\ManyToMany(targetEntity: Reservation::class, mappedBy: 'livres')]
    private Collection $reservations;


    public function __construct()
    {
        $this->reservations = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;
        return $this;
    }

    public function getAuteur(): ?string
    {
        return $this->auteur;
    }

    public function setAuteur(string $auteur): self
    {
        $this->auteur = $auteur;

        return $this;
    }

    public function getEditeur(): ?string
    {
        return $this->editeur;
    }

    public function setEditeur(string $editeur): self
    {
        $this->editeur = $editeur;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getDatePublication(): ?\DateTimeImmutable
    {
        return $this->date_publication;
    }

    public function setDatePublication(\DateTimeImmutable $date_publication): self
    {
        $this->date_publication = $date_publication;
        return $this;
    }


    /**
     * @return Collection<int, Emprunt>
     */
    public function getEmprunts(): Collection
    {
        return $this->emprunts;
    }

    public function addEmprunt(Emprunt $emprunt): self
    {
        if (!$this->emprunts->contains($emprunt)) {
            $this->emprunts->add($emprunt);
            $emprunt->addLivre($this);
        }
        return $this;
    }

    public function removeEmprunt(Emprunt $emprunt): self
    {
        if ($this->emprunts->removeElement($emprunt)) {
            $emprunt->removeLivre($this);
        }
        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations->add($reservation);
            $reservation->addLivre($this);
        }
        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            $reservation->removeLivre($this);
        }
        return $this;
    }

    public function __toString(): string
    {
        return (string) $this->titre;
    }


    public function isDisponible(): bool
    {
        foreach ($this->emprunts as $emprunt) {
            if ($emprunt->getDateRetour() > new \DateTimeImmutable()) {
                return true;
            }
        }
        return false;
    }
}

src/Form/LivreType.php
<?php

namespace App\Form;

use App\Entity\Livre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LivreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('auteur')
            ->add('editeur')
            ->add('genre')
            ->add('date_publication');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Livre::class,
        ]);
    }
}

src/Controller/LivreController.php
<?php

namespace App\Controller;

use App\Entity\Livre;
use App\Form\LivreType;
use App\Repository\LivreRepository;
use App\Repository\ReservationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/')]
class LivreController extends AbstractController
{
    #[Route('/', name: 'app_livre_index', methods: ['GET'])]
    public function index(LivreRepository $livreRepository, Request $request): Response
    {
        return $this->render('livre/index.html.twig', [
            'livres' => $livreRepository->findAll(),
        ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/livre/new', name: 'app_livre_new', methods: ['GET', 'POST'])]
    public function new(Request $request, LivreRepository $livreRepository): Response
    {
        $livre = new Livre();
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $livreRepository->save($livre, true);

            return $this->redirectToRoute('app_livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/new.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }


    #[Route('/livre/{id}', name: 'app_livre_show', methods: ['GET'])]
    public function show(Livre $livre): Response
    {
        return $this->render('livre/show.html.twig', [
            'livre' => $livre,
        ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/livre/{id}/edit', name: 'app_livre_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Livre $livre, LivreRepository $livreRepository): Response
    {
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $livreRepository->save($livre, true);

            return $this->redirectToRoute('app_livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/edit.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/livre/{id}', name: 'app_livre_delete', methods: ['POST'])]
    public function delete(Request $request, Livre $livre, LivreRepository $livreRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $livre->getId(), $request->request->get('_token'))) {
            $livreRepository->remove($livre, true);
        }

        return $this->redirectToRoute('app_livre_index', [], Response::HTTP_SEE_OTHER);
    }


    #[Route('/search', name: "app_livre_search")]
    public function search(Request $request, LivreRepository $livreRepository)
    {
        $searchTerm = $request->query->get('q');

        if (!$searchTerm) {
            return $this->redirectToRoute('app_livre_index');
        }
        $livres = $livreRepository->searchByTitleOrAuthor($searchTerm);

        return $this->render('livre/index.html.twig', [
            'livres' => $livres,
            'searchTerm' => $searchTerm,
        ]);
    }

    // #[Route("/api/google", name: "app_livre_google")]
    // public function google(Request $request, LivreRepository $livreRepository)
    // {
    // }
}

templates/livre/_delete_form.html.twig
<form method="post" action="{{ path('app_livre_delete', {'id': livre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ livre.id) }}">
	<button class="btn btn-primary">Delete</button>
</form>

templates/livre/_form.html.twig
{{ form_start(form) }}
<div class="container">
	{{ form_widget(form) }}
	<button class="btn btn-primary">{{ button_label|default('Save') }}</button>
</div>
{{ form_end(form) }}

templates/livre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Livre
{% endblock %}

{% block body %}
	<div class="container">
		<h1>Edit Livre</h1>
		{{ include('livre/_form.html.twig', {'button_label': 'Update'}) }}
		<a class="" href="{{ path('app_livre_index') }}">back to list</a>
	</div>
{% endblock %}

templates/livre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Liste des livres disponibles
{% endblock %}

{% block body %}
	<div class="container">
		<div class="d-flex gap-5 m-5 align-items-center justify-content-center">
			<h1>Liste des livres disponibles
				{% if is_granted('ROLE_ADMIN') %}
					<a href="{{ path('app_livre_new') }}">
						<button type="button" class="btn btn-primary">Créer</button>
					</a>
				{% endif %}
			</h1>

			<form class="d-flex" role="search" method="GET" action="{{ path('app_livre_search') }}">
				<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" id="searchTerm" name="q">
				<button class="btn btn-outline-success" type="submit">Search</button>
			</form>

		</div>
		<table class="table">
			<thead>
				<tr>
					{% if is_granted('ROLE_ADMIN') %}
						<th>Id</th>
					{% endif %}
					<th>Titre</th>
					<th>Auteur</th>
					<th>Editeur</th>
					<th>Genre</th>
					<th>Disponibilité</th>
					{% if is_granted('ROLE_ADMIN') %}
						<th>Emprunté ?</th>
						<th>Réservé ?</th>
					{% endif %}
					<th>Date de publication</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				{% for livre in livres %}
					<tr>
						{% if is_granted('ROLE_ADMIN') %}
							<td>{{ livre.id }}</td>
						{% endif %}
						<td>{{ livre.titre }}</td>
						<td>{{ livre.auteur }}</td>
						<td>{{ livre.editeur }}</td>
						<td>{{ livre.genre }}</td>
						<td>{{ livre.isDisponible() ? 'Non' : 'Oui' }}</td>
						{% if is_granted('ROLE_ADMIN')%}
							<td>{{ livre.emprunts.isEmpty() ? 'Non' : 'Oui' }}</td>
							<td>{{ livre.reservations.isEmpty() ? 'Non' : 'Oui' }}</td>
						{% endif %}
						<td>{{ livre.datePublication ? livre.datePublication|date('d/m/Y') : '' }}</td>
						<td class="d-flex gap-1">
							<a href="{{ path('app_livre_show', {'id': livre.id}) }}">
								<button type="button" class="btn btn-primary">Voir</button>
							</a>
							{% if livre.isDisponible() and livre.reservations.isEmpty()%}
								{# Ici, le bouton sera afficher au cas ou si une personne veut reserver un livre et devra renvoyer un message/mail a l'admin #}
								<a href="{{ path('app_reservation_index') }}">
									<button type="button" class="btn btn-primary">Réserver</button>
								</a>
							{% endif %}
							{% if is_granted('ROLE_ADMIN') %}
								<a href="{{ path('app_livre_edit', {'id': livre.id}) }}">
									<button type="button" class="btn btn-primary">Modifier</button>
								</a>
								{{ include('livre/_delete_form.html.twig') }}
							{% endif %}
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock %}

templates/livre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Livre{% endblock %}

{% block body %}
    <h1>Create new Livre</h1>

    {{ include('livre/_form.html.twig') }}

    <a href="{{ path('app_livre_index') }}">back to list</a>
{% endblock %}

templates/livre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livre
{% endblock %}

{% block body %}

	<div class="container">
		<h1>Livre</h1>
		{{app.user}}
		<table class="table">
			<tbody>
				<tr>
					<th>Id</th>
					<td>{{ livre.id }}</td>
				</tr>
				<tr>
					<th>Titre</th>
					<td>{{ livre.titre }}</td>
				</tr>
				<tr>
					<th>Auteur</th>
					<td>{{ livre.auteur }}</td>
				</tr>
				<tr>
					<th>Editeur</th>
					<td>{{ livre.editeur }}</td>
				</tr>
				<tr>
					<th>Genre</th>
					<td>{{ livre.genre }}</td>
				</tr>
				<tr>
					<th>IsDisponible</th>
					<td>{{ livre.isDisponible ? 'Oui' : 'Non' }}</td>
				</tr>
				<tr>
					<th>Date_publication</th>
					<td>{{ livre.datePublication ? livre.datePublication|date('Y-m-d') : '' }}</td>
				</tr>
			</tbody>
		</table>

		<a href="{{ path('app_livre_index') }}">back to list</a>

		{% if is_granted('ROLE_ADMIN') %}{% endif %}
	</div>
{% endblock %}